Citizen.CreateThread(function()
	AddTextEntry('rs7', 'Audi RS7')
	AddTextEntry('r8v10', 'Audi R8 V10')
	AddTextEntry('ar8lb', 'Audi R8 Liberty Walk')
	AddTextEntry('gtrc', 'AMG GTR')
	AddTextEntry('e63amg', 'AMG E63')
	AddTextEntry('e63lb', 'AMG E63 Liberty Walk')
	AddTextEntry('e92lb', 'BMW E92 Liberty Walk')
	AddTextEntry('audirs6tk', 'Audi RS6')
	AddTextEntry('e36prb', 'BMW E36')
	AddTextEntry('e46', 'BMW E46')
	AddTextEntry('acs8', 'BMW I8')
	AddTextEntry('m5e60', 'BMW E60')
	AddTextEntry('m3e46', 'BMW M3 E46')
	AddTextEntry('m4', 'BMW M4')
	AddTextEntry('contss18', 'Bentley Continental')
	AddTextEntry('bdragon', 'Bentley Dragon')
	AddTextEntry('c7', 'Corvette C7')
	AddTextEntry('69charger', 'Charger 69')
	AddTextEntry('camaro_ss', 'Camaro SS')
	AddTextEntry('exor', 'Camaro Exorcist')
	AddTextEntry('z2879', 'Camaro Z28')
	AddTextEntry('czl1', 'Camaro ZL1')
	AddTextEntry('delsoleg', 'Del Sol EG')
	AddTextEntry('510', 'Datsun 510')
	AddTextEntry('raid', 'Dodge Raid')
	AddTextEntry('esv', 'Escalade')
	AddTextEntry('66fastback', 'Ford Mustang 66')
	AddTextEntry('mustang19', 'Ford Mustang 2019')
	AddTextEntry('rmodmustang', 'Ford Mustang WideBody')
	AddTextEntry('focusrs', 'Ford Focus RS')
	AddTextEntry('f150', 'Ford F150')
	AddTextEntry('mig', 'Ferrari Enzo')
	AddTextEntry('laferrari17', 'Ferrari LaFerrari')
	AddTextEntry('rudiharley', 'Harley')
	AddTextEntry('hellion6str', 'Hellion V2')
	AddTextEntry('na1', 'Honda NSX')
	AddTextEntry('ap2', 'Honda S2000')
	AddTextEntry('dc5', 'Honda Integra')
	AddTextEntry('filthynsx', 'Honda NSX 2016')
	AddTextEntry('fk8', 'Honda Civic TypeR')
	AddTextEntry('bluecunt', 'Holden SV')
	AddTextEntry('srt8b', 'Jeep Grand Cheroke')
	AddTextEntry('zx10', 'Kawasaki ZX10')
	AddTextEntry('regera', 'Koenigsegg Regera')
	AddTextEntry('lp700r', 'Lamborghini Aventador')
	AddTextEntry('500gtrlam', 'Lamborghini Diablo')
	AddTextEntry('lp670', 'Lamborghini Murcielago')
	AddTextEntry('lwlp670', 'Lamborghini Murcielago WideBody')
	AddTextEntry('rcf', 'Lexus RCF')
	AddTextEntry('rx7rb', 'Mazda RocketBunny RX7')
	AddTextEntry('fnfrx7', 'Mazda RX7')
	AddTextEntry('fc3s', 'Mazda RX7 FC')
	AddTextEntry('na6', 'Mazda Miata')
	AddTextEntry('p1', 'McLaren P1')
	AddTextEntry('650slw', 'McLaren 650')
	AddTextEntry('granlb', 'Maserati Gran Turismo')
	AddTextEntry('cp9a', 'Mitsubishi Evo 6')
	AddTextEntry('evo9', 'Mitsubishi Evo 9')
	AddTextEntry('evo10', 'Mitsubishi Evo 10')
	AddTextEntry('eclipse', 'Mitsubishi Eclipse')
	AddTextEntry('c63', 'Mercedes C63 AMG')
	AddTextEntry('g65amg', 'Mercedes G65 AMG')
	AddTextEntry('gt63', 'Mercedes GT63')
	AddTextEntry('mbw124', 'Mercedes 124')
	AddTextEntry('lwgtr', 'Nissan LibertyWalk GTR')
	AddTextEntry('lwgtr2', 'Nissan LibertyWalk GTR 2')
	AddTextEntry('r35', 'Nissan RHD GTR')
	AddTextEntry('gtr', 'Nissan GTR')
	AddTextEntry('nis13', 'Nissan S13')
	AddTextEntry('er34', 'Nissan R34 4 Door')
	AddTextEntry('s15rb', 'Nissan S15')
	AddTextEntry('300zw', 'Nissan 300zw')
	AddTextEntry('z32', 'Nissan 300zx')
	AddTextEntry('370z', 'Nissan 370z')
	AddTextEntry('por930', 'Porsche 911')
	AddTextEntry('911turbos', 'Porsche 911 Turbo S')
	AddTextEntry('911rwb', 'Porsche 911 Rocket Bunny')
	AddTextEntry('gt2rwb', 'Porsche 911 Rocket Bunny 2')
	AddTextEntry('gt3rs', 'Porsche GT3 RS')
	AddTextEntry('panamera17turbo', 'Porsche Panamera')
	AddTextEntry('918', 'Porsche 918 Spyder')
	AddTextEntry('zondar', 'Pagani Zonda R')
	AddTextEntry('wraith', 'Rolls Royce Wraith')
	AddTextEntry('subwrx', 'Subaru STI WRX')
	AddTextEntry('sultanrsv8', 'Sultan RS MK2')
	AddTextEntry('a80', 'Toyota Supra')
	AddTextEntry('tampa5', 'Tampa V3')
	AddTextEntry('golfp', 'Volkswagen Golf')
	AddTextEntry('r1', 'Yamaha R1')
	AddTextEntry('bnr32', 'Nissan Skyline GTR R32')
	AddTextEntry('mlec', 'Mitsubishi Evolution IX Clinched')
	
end) 

	