--[[ function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey(ADD_TEXT_ENTRY), key, value)
end ]]

Citizen.CreateThread(function()
	AddTextEntry('hemicuda', '1971 Plymouth Hemi Cuda')
	AddTextEntry('titanic2', 'RMS Titanic')
	AddTextEntry('camaross', 'Camaro SS')
	AddTextEntry('jeep2012', '2012 Jeep Rubicon')
	AddTextEntry('mgt', '2016 Ford Mustang 5.0')
	AddTextEntry('skyline', 'Nissan GTR R34')
	AddTextEntry('16challenger', '2016 Dodge Challenger')
	AddTextEntry('m5f90', '2017 BMW M5 F90')
	AddTextEntry('plmthf58', '1958 Plymouth Fury')
	AddTextEntry('silv86', '1986 Chevrolet Silverado')
end) 