--[[ function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey(ADD_TEXT_ENTRY), key, value)
end ]]

Citizen.CreateThread(function()
	AddTextEntry('trhawk', '2018 Dodge TrackHawk')
	AddTextEntry('2015polstang', '2015 Ford Mustang GT500')
	AddTextEntry('polvic2', '2011 Ford Crown Victoria')
	AddTextEntry('poltaurus', '2016 Ford Taurus')
	AddTextEntry('18chgrleo', '2018 Dodge Charger')
	AddTextEntry('polchar', '2014 Dodge Charger')
	AddTextEntry('expleo', '2016 Ford Explorer')
    AddTextEntry('polraptor', '2020 Ford F150 Raptor')
	AddTextEntry('code3gator', 'JD Police Gator')
	AddTextEntry('poltah', '2015 Chevrolet Tahoe')
	AddTextEntry('sspres', '2012 Swat Suburban')
	AddTextEntry('sahpinsurgent', 'Swat Insurgent')
	AddTextEntry('pbus2', 'Prison Party Bus')
	AddTextEntry('tahoe', '2020 Chevrolet Tahoe')
	AddTextEntry('code3cap', '2013 Chevrolet Caprice')

end) 